### ISSUE TITLE
Hide Pin Icon

### ISSUE THREAD

**Issue by FlyingRatBull** [Sheeplet1/obsidian-pin-enhancer#5]
It would be really helpful to have the optional ability to hide the pin icon as it would free up a lot of space if you don't intend to unpin any of the pinned tabs:

![Image](https://github.com/user-attachments/assets/83359302-4201-402e-852b-f187c90cc135)

would become

![Image](https://github.com/user-attachments/assets/5401dc86-e373-4649-9ea2-f48a68dc56b4)

**Comment by FlyingRatBull** [comment]
Thanks, @parkeraddison. For anyone interested, I settled with the following:

```css
.workspace-tab-header:has(.mod-pinned) .mod-pinned {
    display: none;
}

.workspace .mod-root .workspace-tab-header:has(.mod-pinned) {
    width: 30px !important;
    flex: none !important;
}
```
